name: Release Composer

on:
  # Activates when a push targets the files under "paths" in main.
  push:
    branches:
      - main
    paths:
      - 'addons/composer_godot/plugin.cfg'
      - 'addons/composer_godot/Composer.gd'
      - 'addons/composer_godot/plugin_composer.gd'
      - 'addons/composer_godot/icon.png'
      - 'README.md'
      - 'LICENSE'

  # Enables manual trigger from the actions tab at the repository.
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new Composer release'
        default: 'true'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Composer zip
        run: |
          mkdir -p composer-release/addons/composer_godot
          cp addons/composer_godot/plugin.cfg composer-release/addons/composer_godot/
          cp addons/composer_godot/Composer.gd composer-release/addons/composer_godot/
          cp addons/composer_godot/plugin_composer.gd composer-release/addons/composer_godot/
          cp addons/composer_godot/icon.png composer-release/addons/composer_godot/
          cp README.md LICENSE composer-release/
          cd composer-release
          zip -r ../Composer.zip .

      - name: Create latest release
      # Creates a release under the "latest" tag and releases these files.
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Composer"
          files: |
            Composer.zip
